server.port=8080

# PostgreSQL Database Configurations
# E.g. run: CREATE DATABASE smartqueue;
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.oafdwnkimddbfxtoiaqm
spring.datasource.password=supabase@23

# JPA / Hibernate Configurations
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
